spring:
  application:
    name: order
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/imc_springcloud_sell?characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Bruse
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
env:
  dev-test
label:
  release
