spring
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imc_springcloud_sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Bruse
  jpa:
    show-sql: true
